# Generated by Django 4.2 on 2023-05-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
